<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #4a5568; padding-bottom: 10px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th { background-color: #4a5568; color: white; padding: 10px; text-align: left; }
        td { border-bottom: 1px solid #edf2f7; padding: 10px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 10px; color: #718096; }
    </style>
</head>
<body>
    <div class="header">
        <h2>{{ config('app.name') }} - Employee Report</h2>
        <p>Generated: {{ now()->toDayDateTimeString() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Position</th>
                <th>Salary</th>
                <th>Department</th>
            </tr>
        </thead>
        <tbody>
            @foreach($employees as $employee)
            <tr>
                <td>{{ $employee->id }}</td>
                <td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
                <td>{{ $employee->email }}</td>
                <td>{{ $employee->phone ?? 'N/A'}}</td>
                <td>{{ $employee->position }}</td>
                <td>{{ number_format($employee->salary, 2) }}</td>
                <td>{{ $employee->department->dept_name ?? 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Page generated by Employee Management System
    </div>
</body>
</html>