<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; }
        .header { text-align: center; border-bottom: 2px solid #4a5568; padding-bottom: 10px; margin-bottom: 20px; }
        .filters { background-color: #f7fafc; padding: 10px; margin-bottom: 15px; border-left: 4px solid #4a5568; font-size: 12px; }
        .filters p { margin: 5px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #4a5568; color: white; padding: 10px; text-align: left; font-size: 13px; }
        td { border-bottom: 1px solid #edf2f7; padding: 10px; font-size: 12px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 10px; color: #718096; padding-top: 10px; border-top: 1px solid #e2e8f0; }
        .count { margin-top: 15px; font-size: 12px; color: #4a5568; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h2>{{ config('app.name') }} - Employee Report</h2>
        <p>Generated: {{ now()->toDayDateTimeString() }}</p>
    </div>

    @if(request('search') || request('department_filter'))
        <div class="filters">
            <p><strong>Applied Filters:</strong></p>
            @if(request('search'))
                <p>• Search: <strong>{{ request('search') }}</strong></p>
            @endif
            @if(request('department_filter'))
                @php
                    $dept = \App\Models\Department::find(request('department_filter'));
                @endphp
                <p>• Department: <strong>{{ $dept->dept_name ?? 'N/A' }}</strong></p>
            @endif
        </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Photo</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Position</th>
                <th>Salary</th>
                <th>Department</th>
            </tr>
        </thead>
        <tbody>
            @forelse($employees as $employee)
            <tr>
                <td>{{ $employee->id }}</td>
                <td class="px-6 py-4 whitespace-nowrap">
                    @if($employee->photo_path && file_exists($employee->photo_path))
                        <img src="{{ $employee->photo_path }}" 
                            style="width: 30px; height: 30px; object-fit: cover; border-radius: 50%;">
                    @else
                        <div style="width: 30px; height: 30px; background-color: #e5e7eb; display: flex; align-items: center; justify-content: center; border-radius: 50%; color: #666; font-weight: bold; font-size: 10px;">
                            {{ strtoupper(substr($employee->first_name,0,1).substr($employee->last_name,0,1)) }}
                        </div>
                    @endif
                </td>
                <td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
                <td>{{ $employee->email }}</td>
                <td>{{ $employee->phone ?? 'N/A'}}</td>
                <td>{{ $employee->position }}</td>
                <td>${{ number_format($employee->salary, 2) }}</td>
                <td>{{ $employee->department->dept_name ?? 'N/A' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center; padding: 20px;">No employees found matching the filters.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="count">
        Total Records: {{ $employees->count() }}
    </div>

    <div class="footer">
        Page generated by Employee Management System
    </div>
</body>
</html>